using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.SceneManagement;

public class PauseMenu : MonoBehaviour
{
   public static bool isGamePaused;
   public GameObject pauseMenuUI;
 
   // Update is called once per frame
   void Update()
   {
       //User input to pause/resume game
       if(Input.GetKeyDown(KeyCode.Escape))
       {
           if(isGamePaused)
           {
               Resume();
           }
           else
           {
               Pause();
           }
       }
   }
 
   public void Resume()
   {
       //deactivate pause menu and unfreeze game
       pauseMenuUI.SetActive(false);
       Time.timeScale = 1f;
       isGamePaused = false;
   }
 
   void Pause()
   {
       //activate pause menu and freeze game
       pauseMenuUI.SetActive(true);
       Time.timeScale = 0f;
       isGamePaused = true;
   }
 
   public void LoadMenu()
   {
       //return to main menu
       Time.timeScale = 1f;
       SceneManager.LoadScene("Menu Scene");
   }
 
   public void QuitGame()
   {
       Debug.Log("Quitting Game...");
       //exit application
       Application.Quit();
   }
}
